# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7012450f34d748ec6806b804626922aa85afad5eee87b0830b3b7c3badaf6250d81a00bef0fc3692a64ccd70ab32b71a33e4a41d7d2705219a327d24f071f470

test:
  secret_key_base: d33c511b86ace0b41f1ce410574e6090c066cfb04e73215e19a0e95938fddf75165f0915209f5c015be82d1cd353b410551f1da9104e6ee13e8e46c3c28dcedf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
